
POST http://localhost:3000/post
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJkLTE3MjEyMDY2MjA0MjAiLCJ0eXAiOiJKV1QiLCJ2ZXJzaW9uIjoiNSIsImFsZyI6IlJTMjU2In0.eyJpYXQiOjE3MjE1MTAzNDMsImV4cCI6MTcyMTUxMzk0Mywic3ViIjoiY2E0NDg3YzQtM2Q2MC00NTExLThlZjMtMTQzZWJiMTM0MDQzIiwidElkIjoicHVibGljIiwicnN1YiI6ImNhNDQ4N2M0LTNkNjAtNDUxMS04ZWYzLTE0M2ViYjEzNDA0MyIsInNlc3Npb25IYW5kbGUiOiIxMzY3YjBiYy1mMDVjLTQxYWUtODgzMy05YmUxMDliZTA0OGYiLCJyZWZyZXNoVG9rZW5IYXNoMSI6IjNhNjMwOTU4ODU3NjE5MTcyZDMwOGFkNzg1OTZkNWM3ODlhN2ZiOGQ2OWYzYTcyNjNkMjdjZjRmY2FjN2IyMTAiLCJwYXJlbnRSZWZyZXNoVG9rZW5IYXNoMSI6bnVsbCwiYW50aUNzcmZUb2tlbiI6bnVsbCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwL2F1dGgifQ.k0tWVbh1uHQ1WWTfK31XWizbh7O-eTv7SQjiTgUNy_IVgBhz0N-tBVqjpPD_koLvTP-liWX-vdawB9fZt3dWYcpvBD22jGr7AB8lpqkrKEj81Qs20iqk1HSa_U7-38OXVYgyf0cc2HpKsw0fuWg1EO_GyYV53k7BVJ36MPgm0avENYqFjaAqFJWnYY9obpGl-Velzio6fQ1-PpN792N3xHotuh2CtHb6jggrGQRPUbQNFODKfItZ_zy_rIpTUP7J7fZBvac46RiTI5FhIV89TB2wgqs1DH2XLKP6tPDDdqPenbkcpLguzptultTZAohTrDMRv2VBPbcat0eklW_hfw

{
    "content": "My post"
}

###
GET http://localhost:3000/post/2

###
GET http://localhost:3000/post

###
PATCH http://localhost:3000/post/2
Content-Type: application/json

{
    "content": "My funny post"
}

###
DELETE http://localhost:3000/post/1
